partial class FrmLoginScreen
{
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        private Panel PanelLeft;
            private PictureBox LogoImage;
            private Label LblWelcome;
            private Label LblDescription;
        private Panel PanelRight;
            private Label LblEmail;
            private TextBox EditEmail;
            private Label LblPassword;
            private TextBox EditPassword;
            private CheckBox ChkRememberMe;
            private Label LblForgotPassword;
            private Button BtnLogin;
            private Button BtnSignUp;
            private Label LblFollow;
            private Panel PanelSocialIcons;
                private PictureBox IconFacebook;
                private PictureBox IconTwitter;
                private PictureBox IconInstagram;

        private void InitializeComponent()
        {
            this.ClientSize = new System.Drawing.Size(900, 600);
            this.ClientSize = new System.Drawing.Size(900, 600);
            this.Text = "Login Screen";
        this.PanelLeft = new Panel();
        this.PanelLeft.Text = " ";
        this.PanelLeft.Location = new System.Drawing.Point(0, 0);
        this.PanelLeft.Width = 450;
        this.PanelLeft.Height = 600;
        PanelLeft.BackColor = System.Drawing.Color.FromArgb(46, 65, 245);
        this.Controls.Add(this.PanelLeft);
            this.LogoImage = new PictureBox();
            this.LogoImage.Location = new System.Drawing.Point(150, 100);
            this.LogoImage.Width = 150;
            this.LogoImage.Height = 300;
            this.PanelLeft.Controls.Add(this.LogoImage);
            this.LblWelcome = new Label();
            this.LblWelcome.Location = new System.Drawing.Point(30, 420);
            this.LblWelcome.Text = "Welcome to BuiderUI - Login !";
            LblWelcome.Font = new System.Drawing.Font(LblWelcome.Font.FontFamily, 24);
            LblWelcome.ForeColor = System.Drawing.Color.FromArgb(255, 255, 255);
            this.PanelLeft.Controls.Add(this.LblWelcome);
            this.LblDescription = new Label();
            this.LblDescription.Location = new System.Drawing.Point(30, 460);
            this.LblDescription.Width = 380;
            this.LblDescription.Text = "A simple login screen render using BuilderUI, JSON based.";
            LblDescription.Font = new System.Drawing.Font(LblDescription.Font.FontFamily, 12);
            LblDescription.ForeColor = System.Drawing.Color.FromArgb(208, 208, 255);
            this.PanelLeft.Controls.Add(this.LblDescription);
        this.PanelRight = new Panel();
        this.PanelRight.Location = new System.Drawing.Point(450, 0);
        this.PanelRight.Width = 450;
        this.PanelRight.Height = 600;
        PanelRight.BackColor = System.Drawing.Color.FromArgb(255, 255, 255);
        this.Controls.Add(this.PanelRight);
            this.LblEmail = new Label();
            this.LblEmail.Location = new System.Drawing.Point(80, 100);
            this.LblEmail.Text = "Email address";
            LblEmail.Font = new System.Drawing.Font(LblEmail.Font.FontFamily, 10);
            LblEmail.ForeColor = System.Drawing.Color.FromArgb(0, 0, 0);
            this.PanelRight.Controls.Add(this.LblEmail);
            this.EditEmail = new TextBox();
            this.EditEmail.Location = new System.Drawing.Point(80, 120);
            this.EditEmail.Width = 300;
            this.EditEmail.Text = "name@mail.com";
            this.PanelRight.Controls.Add(this.EditEmail);
            this.LblPassword = new Label();
            this.LblPassword.Location = new System.Drawing.Point(80, 150);
            this.LblPassword.Text = "Password";
            LblPassword.Font = new System.Drawing.Font(LblPassword.Font.FontFamily, 10);
            LblPassword.ForeColor = System.Drawing.Color.FromArgb(0, 0, 0);
            this.PanelRight.Controls.Add(this.LblPassword);
            this.EditPassword = new TextBox();
            this.EditPassword.Location = new System.Drawing.Point(80, 170);
            this.EditPassword.Width = 300;
            this.PanelRight.Controls.Add(this.EditPassword);
            this.ChkRememberMe = new CheckBox();
            this.ChkRememberMe.Location = new System.Drawing.Point(80, 220);
            this.ChkRememberMe.Text = "Remember me";
            this.PanelRight.Controls.Add(this.ChkRememberMe);
            this.LblForgotPassword = new Label();
            this.LblForgotPassword.Location = new System.Drawing.Point(270, 222);
            this.LblForgotPassword.Text = "Forgot password?";
            LblForgotPassword.ForeColor = System.Drawing.Color.FromArgb(46, 65, 245);
            this.PanelRight.Controls.Add(this.LblForgotPassword);
            this.BtnLogin = new Button();
            this.BtnLogin.Location = new System.Drawing.Point(80, 270);
            this.BtnLogin.Width = 100;
            this.BtnLogin.Text = "Login";
            this.PanelRight.Controls.Add(this.BtnLogin);
            this.BtnSignUp = new Button();
            this.BtnSignUp.Location = new System.Drawing.Point(190, 270);
            this.BtnSignUp.Width = 100;
            this.BtnSignUp.Text = "Sign up";
            this.PanelRight.Controls.Add(this.BtnSignUp);
            this.LblFollow = new Label();
            this.LblFollow.Location = new System.Drawing.Point(80, 330);
            this.LblFollow.Text = "FOLLOW";
            this.PanelRight.Controls.Add(this.LblFollow);
            this.PanelSocialIcons = new Panel();
            PanelSocialIcons.BackColor = System.Drawing.Color.FromArgb(255, 255, 255);
            this.PanelSocialIcons.Text = "  .  ";
            this.PanelSocialIcons.Location = new System.Drawing.Point(80, 360);
            this.PanelSocialIcons.Width = 150;
            this.PanelSocialIcons.Height = 30;
            this.PanelRight.Controls.Add(this.PanelSocialIcons);
                this.IconFacebook = new PictureBox();
                this.IconFacebook.Location = new System.Drawing.Point(0, 0);
                this.IconFacebook.Width = 30;
                this.IconFacebook.Height = 30;
                this.PanelSocialIcons.Controls.Add(this.IconFacebook);
                this.IconTwitter = new PictureBox();
                this.IconTwitter.Location = new System.Drawing.Point(40, 0);
                this.IconTwitter.Width = 30;
                this.IconTwitter.Height = 30;
                this.PanelSocialIcons.Controls.Add(this.IconTwitter);
                this.IconInstagram = new PictureBox();
                this.IconInstagram.Location = new System.Drawing.Point(80, 0);
                this.IconInstagram.Width = 30;
                this.IconInstagram.Height = 30;
                this.PanelSocialIcons.Controls.Add(this.IconInstagram);
        }
}
